### ISSUE TITLE
fix: broken link in email notifications

### ISSUE THREAD

**Issue by mikkel1ea** [equinor/chemcom-api#125]

**Comment by bonyfusbouvet** [comment]
@mikkel1ea should be fixed. You can try this on dev.

**Comment by mikkel1ea** [comment]
Still looks like this in dev, my language change is there. But the links are still the same:

![Image](https://github.com/equinor/chemcom-api/assets/111305377/5964542a-ea1f-4902-88d3-c5e3d8349497)
[You can view the results of the emails here](https://outlook.office.com/mail/gm_chemcom@equinor.com)
